name: Măng cụt
en_name: Mangcut
title: Viết để thay đổi nhận thức
en_title: Truong Hong Thi's Personal Page
description: Mở những ô cửa mới để cùng nhìn thế giới.
en_description: Truong Hong Thi on Programming and Life
permalink: /:categories/:year-:month-:day-:title.html
url: http://www.mangcut.vn
author: Trương Hồng Thi
en_author: Truong Hong Thi
highlighter: pygments
recommended_series_id: world
markdown: kramdown
kramdown:
  use_coderay: false
  coderay:
    coderay_css: class
syntax:
  hilight: false
  css: prism
  js: /js/prism.js
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to pages
    values:
      is_page: true # automatically set is_page=true for all posts
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts