name: Blog Măng Cụt
en_name: Blog Măng Cụt
title: Trương Hồng Thi
en_title: Truong Hong Thi's Personal Page
description: Cùng mở những ô cửa mới.
en_description: Truong Hong Thi on Programming and Life
url: http://www.mangcut.vn
author: Trương Hồng Thi
en_author: Truong Hong Thi
highlighter: rouge
exclude: [temp,tmp,misc]
markdown: kramdown
kramdown:
  auto_ids: false
  enable_coderay: false
  coderay:
    coderay_css: class
syntax:
  hilight: false
  css: prism
  js: /js/prism.js
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      comment: false
      auto_email: false
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      comment: false
      auto_email: true
      author_id: thith
      permalink: /:categories/:title.html
  -
    scope:
      path: "blog"
      type: posts
    values:
      permalink: /blog/:year-:month-:day-:title.html
  -
    scope:
      path: "tho"
      type: posts
    values:
      author_id: thientx
      font_size: 112.5%
      excerpt_separator: <!--more-->