name: Blog Măng Cụt
en_name: Blog Măng Cụt
title: Trương Hồng Thi
en_title: Truong Hong Thi's Personal Page
description: Mở những ô cửa mới để cùng quan sát thế giới.
en_description: Truong Hong Thi on Programming and Life
permalink: /:categories/:year-:month-:day-:title.html
url: http://www.mangcut.vn
author: Trương Hồng Thi
en_author: Truong Hong Thi
highlighter: pygments
recommended_series_id: world
exclude: [temp,tmp,misc]
markdown: kramdown
kramdown:
  enable_coderay: false
  coderay:
    coderay_css: class
syntax:
  hilight: false
  css: prism
  js: /js/prism.js
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      comment: false
      auto_email: false
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      comment: false
      auto_email: true